/*
 * Copyright © 2019 Cask Data, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not
 * use this file except in compliance with the License. You may obtain a copy of
 * the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
 * WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
 * License for the specific language governing permissions and limitations under
 * the License.
 */

package io.cdap.plugin.oracle;

import io.cdap.cdap.api.data.schema.Schema;

/**
 * Oracle constants.
 */
public class OracleConstants {

  private OracleConstants() {
    throw new AssertionError("Should not instantiate static utility class.");
  }

  /**
   * Oracle plugin name.
   */
  public static final String PLUGIN_NAME = "Oracle";

  /**
   * Oracle Service Cloud API root path including API version which corresponds to the
   * Connect Common Object Model (CCOM) version v1.4.
   */
  public static final String API_ROOT_PATH = "/services/rest/connect/v1.4/";

  /**
   * Configuration property name used to specify the mode of authentication to use.
   */
  public static final String AUTHENTICATION_TYPE = "authenticationType";

  /**
   * Configuration property name used to specify REST server URL from the account creation email received from Oracle.
   */
  public static final String SERVER_URL = "serverUrl";

  /**
   * Configuration property name used to specify Oracle Service Cloud username.
   */
  public static final String USERNAME = "username";

  /**
   * Configuration property name used to specify Oracle Service Cloud password.
   */
  public static final String PASSWORD = "password";

  /**
   * Configuration property name used to specify the schema of the entries.
   */
  public static final String SCHEMA = "schema";

  /**
   * Configuration property name used to specify session ID for Oracle Service Cloud.
   */
  public static final String SESSION_ID = "sessionId";

  /**
   * Configuration property name used to specify OAuth access token, generated by an external identity provider.
   */
  public static final String ACCESS_TOKEN = "accessToken";

  /**
   * Configuration property name used to specify the type of query.
   */
  public static final String QUERY_TYPE = "queryType";

  /**
   * Configuration property name used to specify an object to pull from Oracle Service Cloud. Examples of objects are
   * Accounts, Analytics Reports, Opportunities, etc.
   */
  public static final String SERVICE_CLOUD_OBJECT = "serviceCloudObject";

  /**
   * Configuration property name used to specify ROQL query that specifies the data to import.
   */
  public static final String QUERY = "query";

  /**
   * Configuration property name used to specify field in the selected object to sort the results by.
   */
  public static final String SORT_BY = "sortBy";

  /**
   * Configuration property name used to specify the sort direction: Ascending or Descending.
   */
  public static final String SORT_DIRECTION = "sortDirection";

  /**
   * Configuration property name used to filter data to include only records which have modification date greater than
   * or equal to the specified date.
   */
  public static final String START_DATE = "startDate";

  /**
   * Configuration property name used to filter data to include only records which have modification date less than the
   * specified date.
   */
  public static final String END_DATE = "endDate";

  /**
   * Oracle Service Cloud Object is mapped to a record with
   * "{@value OracleConstants.LinkedObject#LINKS}" for an array of {@link Link}.
   */
  public static class LinkedObject {
    public static final String LINKS = "links";

    public static Schema schema(String fieldName) {
      return Schema.recordOf(
        fieldName + "-linked-object-record",
        Schema.Field.of(LINKS, Schema.arrayOf(Link.schema(fieldName)))
      );
    }
  }

  /**
   * Oracle Service Cloud Object is mapped to a record with
   * "{@value OracleConstants.OracleObject#ID}" for the unique identifier of the object,
   * "{@value OracleConstants.OracleObject#CREATED_TIME}" for the date and time when the asset was created,
   * "{@value OracleConstants.OracleObject#UPDATED_TIME}" for the date and time when the asset was last updated,
   * "{@value OracleConstants.OracleObject#LOOKUP_NAME}" for the name used to look up the object.
   */
  public static class OracleObject {
    public static final String ID = "id";
    public static final String CREATED_TIME = "createdTime";
    public static final String UPDATED_TIME = "updatedTime";
    public static final String LOOKUP_NAME = "lookupName";
  }

  /**
   * Oracle Service Cloud Link is mapped to a record with
   * "{@value OracleConstants.Link#REL}" for the relationship between two linked documents,
   * "{@value OracleConstants.Link#HREF}" for the reference to the linked document,
   * "{@value OracleConstants.Link#MEDIA_TYPE}" for the media type.
   */
  public static class Link {
    public static final String REL = "rel";
    public static final String HREF = "href";
    public static final String MEDIA_TYPE = "mediaType";

    public static Schema schema(String fieldName) {
      return Schema.recordOf(
        fieldName + "-link-record",
        Schema.Field.of(REL, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
        Schema.Field.of(HREF, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
        Schema.Field.of(MEDIA_TYPE, Schema.nullableOf(Schema.of(Schema.Type.STRING)))
      );
    }
  }

  /**
   * An Oracle Service Cloud ID which has an associated name string. These IDs can be set by either value or name.
   * "{@value OracleConstants.IdLookupName#ID}" for the resource's identifier,
   * "{@value OracleConstants.IdLookupName#LOOKUP_NAME}" for the resource's lookup name.
   */
  public static class IdLookupName {
    public static final String ID = "id";
    public static final String LOOKUP_NAME = "lookupName";

    public static Schema schema(String fieldName) {
      return Schema.recordOf(
        fieldName + "-id-lookup-name-record",
        Schema.Field.of(ID, Schema.nullableOf(Schema.of(Schema.Type.INT))),
        Schema.Field.of(LOOKUP_NAME, Schema.nullableOf(Schema.of(Schema.Type.STRING)))
      );
    }
  }

  /**
   * Oracle Service Cloud Account Attributes mapped to a record with
   * "{@value OracleConstants.AccountAttributes#ACCOUNT_LOCKED}" for the attribute which indicates whether the account
   * is temporarily locked,
   * "{@value OracleConstants.AccountAttributes#CAN_MODIFY_EMAIL_SIGNATURE}" for the attribute which indicates whether
   * the staff member can modify the email signature,
   * "{@value OracleConstants.AccountAttributes#FORCE_PASSWORD_CHANGE}" for the attribute which indicates whether
   * the staff member must change the password at the next login,
   * "{@value OracleConstants.AccountAttributes#INFREQUENT_USER}" for the attribute which indicates whether the staff
   * member is considered as an infrequent user seat, as opposed to a full seat,
   * "{@value OracleConstants.AccountAttributes#PASSWORD_NEVER_EXPIRES}" for the attribute which indicates whether the
   * staff member's account password never expires,
   * "{@value OracleConstants.AccountAttributes#PERMANENTLY_DISABLED}" for the attribute which indicates whether the
   * staff member's account is permanently disabled,
   * "{@value OracleConstants.AccountAttributes#STAFF_ASSIGNMENT_DISABLED}" for the attribute which indicates whether
   * the staff member's account cannot be assigned to incidents, answers, opportunities, and tasks,
   * "{@value OracleConstants.AccountAttributes#VIEWS_REPORTS_DISABLED}" for the attribute which indicates whether
   * the staff member's account cannot be included in the list for filters in reports,
   * "{@value OracleConstants.AccountAttributes#VIRTUAL_ACCOUNT}" for the attribute which indicates whether the
   * staff member's account is virtual.
   */
  public static class AccountAttributes {
    public static final String ACCOUNT_LOCKED = "accountLocked";
    public static final String CAN_MODIFY_EMAIL_SIGNATURE = "canModifyEmailSignature";
    public static final String FORCE_PASSWORD_CHANGE = "forcePasswordChange";
    public static final String INFREQUENT_USER = "infrequentUser";
    public static final String PASSWORD_NEVER_EXPIRES = "passwordNeverExpires";
    public static final String PERMANENTLY_DISABLED = "permanentlyDisabled";
    public static final String STAFF_ASSIGNMENT_DISABLED = "staffAssignmentDisabled";
    public static final String VIEWS_REPORTS_DISABLED = "viewsReportsDisabled";
    public static final String VIRTUAL_ACCOUNT = "virtualAccount";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-attributes-record",
      Schema.Field.of(ACCOUNT_LOCKED, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(CAN_MODIFY_EMAIL_SIGNATURE, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(FORCE_PASSWORD_CHANGE, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(INFREQUENT_USER, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(PASSWORD_NEVER_EXPIRES, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(PERMANENTLY_DISABLED, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(STAFF_ASSIGNMENT_DISABLED, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(VIEWS_REPORTS_DISABLED, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(VIRTUAL_ACCOUNT, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN)))
    );
  }

  /**
   * Oracle Service Cloud Account emails mapped to a record with
   * "{@value OracleConstants.AccountEmails#ADDRESS}" for the string value of the email address,
   * "{@value OracleConstants.AccountEmails#ADDRESS_TYPE}"  an ID which has an associated name string(these IDs can
   * be set by either value or name),
   * "{@value OracleConstants.AccountEmails#CERTIFICATE}" for the associated public email certificate used to encrypt
   * outgoing emails,
   * "{@value OracleConstants.AccountEmails#INVALID}" for attribute which indicates whether the email address is
   * disabled.
   */
  public static class AccountEmails {
    public static final String ADDRESS = "address";
    public static final String ADDRESS_TYPE = "addressType";
    public static final String CERTIFICATE = "certificate";
    public static final String INVALID = "invalid";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-emails-record",
      Schema.Field.of(ADDRESS, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(ADDRESS_TYPE, Schema.nullableOf(IdLookupName.schema("account-address-type-record"))),
      Schema.Field.of(CERTIFICATE, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(INVALID, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN)))
    );
  }

  /**
   * Oracle Service Cloud Account name mapped to a record with
   * "{@value OracleConstants.AccountName#FIRST}" for the first name of the person,
   * "{@value OracleConstants.AccountName#LAST}"  for the last name of the person.
   */
  public static class AccountName {
    public static final String FIRST = "first";
    public static final String LAST = "last";

    public static Schema schema(String fieldName) {
      return Schema.recordOf(
        fieldName + "-account-name-record",
        Schema.Field.of(FIRST, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
        Schema.Field.of(LAST, Schema.nullableOf(Schema.of(Schema.Type.STRING)))
      );
    }
  }

  /**
   * Oracle Service Cloud Account phone mapped to a record with
   * "{@value OracleConstants.AccountPhone#NUMBER}" for the free-form phone number including non-numeric characters.
   * For example, 1 (406) 522-4200,
   * "{@value OracleConstants.AccountPhone#PHONE_TYPE}" for an ID which has an associated name string(these IDs can be
   * set by either value or name),
   * "{@value OracleConstants.AccountPhone#RAW_NUMBER}" for the automatically populated numeric string derived by
   * excluding the non-numeric characters from the value of the Number attribute. For example, if the Number attribute
   * has a value of 1 (406) 522-4200, this field is populated as 14065224200.
   */
  public static class AccountPhone {
    public static final String NUMBER = "number";
    public static final String PHONE_TYPE = "phoneType";
    public static final String RAW_NUMBER = "rawNumber";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-phone-record",
      Schema.Field.of(NUMBER, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(PHONE_TYPE, Schema.nullableOf(IdLookupName.schema("account-phone-type-record"))),
      Schema.Field.of(RAW_NUMBER, Schema.nullableOf(Schema.of(Schema.Type.STRING)))
    );
  }

  /**
   * Oracle Service Cloud Account sales settings mapped to a record with
   * "{@value OracleConstants.AccountSalesSettings#DEFAULT_CURRENCY}" for an ID which has an associated name string
   * (these IDs can be set by either value or name),
   * "{@value OracleConstants.AccountSalesSettings#TERRITORY}" for the specific geographical sales region. Sales
   * representatives can be assigned specific territories for opportunity assignment. It is the reference to a
   * resource in 'salesTerritories' collection. Only ID or lookupName can be provided to specify the resource.
   */
  public static class AccountSalesSettings {
    public static final String DEFAULT_CURRENCY = "defaultCurrency";
    public static final String TERRITORY = "territory";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-sales-settings-record",
      Schema.Field.of(DEFAULT_CURRENCY, Schema.nullableOf(IdLookupName.schema("default-currency"))),
      Schema.Field.of(TERRITORY, Schema.nullableOf(IdLookupName.schema("territory")))
    );
  }

  /**
   * Oracle Service Cloud Account service settings mapped to a record with
   * "{@value OracleConstants.AccountServiceSettings#SCREEN_POP_PORT}" for the port number assigned for screen-pop
   * alerts for the staff account. It is used in Citrix and Terminal Services environments where there are multiple
   * agents logged in to different sessions on the same machine.
   */
  public static class AccountServiceSettings {
    public static final String SCREEN_POP_PORT = "screenPopPort";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-service-settings-record",
      Schema.Field.of(SCREEN_POP_PORT, Schema.nullableOf(Schema.of(Schema.Type.INT)))
    );
  }

  /**
   * The Account represents a staff member in Oracle Service Cloud. Examples of staff members are customer sales
   * representatives, sales agents, site administrators, and so on.
   * Oracle Service Cloud Account is mapped to a record with
   * "{@value OracleConstants.Account#ACCOUNT_HIERARCHY}" for the reference to a resource in 'accounts' collection,
   * "{@value OracleConstants.Account#ATTRIBUTES}" for the group of flags used for setting certain features or special
   * behaviors for an account,
   * "{@value OracleConstants.Account#COUNTRY}" for the the details about the countries and provinces which are used to
   * maintain accurate address information for the organizations and contacts in Oracle Service Cloud(reference to a
   * resource 'countries' collection),
   * "{@value OracleConstants.Account#DISPLAY_NAME}" for the display name of the account,
   * "{@value OracleConstants.Account#DISPLAY_ORDER}" for the order in which this staff account is displayed relative
   * to other members of the same group,
   * "{@value OracleConstants.Account#EMAIL_NOTIFICATION}" for an ID which has an associated name string(these IDs can
   * be set by either value or name),
   * "{@value OracleConstants.Account#EMAILS}" for the email address and its associated information,
   * "{@value OracleConstants.Account#LOGIN}" for the user name used for authentication,
   * "{@value OracleConstants.Account#MANAGER}" for the account that represents a staff member in Oracle Service Cloud.
   * Examples of staff members are customer sales representatives, sales agents, site administrators, and so on.
   * It is the reference to a resource in 'accounts' collection. Only ID or lookupName can be provided to specify the
   * resource.
   * "{@value OracleConstants.Account#NAME}" for the full name of the person, including the first name and the last
   * name,
   * "{@value OracleConstants.Account#NAME_FURIGANA}" for the full name of the person, including the first name and the
   * last name,
   * "{@value OracleConstants.Account#NOTIFICATION_PENDING}" for the attribute which indicates whether any notifications
   * are pending,
   * "{@value OracleConstants.Account#PASSWORD_EXPIRATION_TIME}" for the date and time when the password is set to
   * expire,
   * "{@value OracleConstants.Account#PHONES}" for the details related to the phone number,
   * "{@value OracleConstants.Account#PROFILE}" for an ID which has an associated name string(these IDs can be set by
   * either value or name),
   * "{@value OracleConstants.Account#SALES_SETTINGS}" for the sales-related information of the account,
   * "{@value OracleConstants.Account#SERVICE_SETTINGS}" for the service-related information of the account,
   * "{@value OracleConstants.Account#SIGNATURE}" for the email signature of the account,
   * "{@value OracleConstants.Account#STAFF_GROUP}" for an ID which has an associated name string(these IDs can be set
   * by either value or name).
   * <p>
   * See:
   * <a
   * href="https://docs.oracle.com/en/cloud/saas/service/19c/cxsvc/op-services-rest-connect-v1.4-accounts-id-get.html">
   * Get an account
   * </a>
   */
  public static class Account extends OracleObject {
    public static final String ACCOUNT_HIERARCHY = "accountHierarchy";
    public static final String ATTRIBUTES = "attributes";
    public static final String COUNTRY = "country";
    public static final String DISPLAY_NAME = "displayName";
    public static final String DISPLAY_ORDER = "displayOrder";
    public static final String EMAIL_NOTIFICATION = "emailNotification";
    public static final String EMAILS = "emails";
    public static final String LOGIN = "login";
    public static final String MANAGER = "manager";
    public static final String NAME = "name";
    public static final String NAME_FURIGANA = "nameFurigana";
    public static final String NOTIFICATION_PENDING = "notificationPending";
    public static final String PASSWORD_EXPIRATION_TIME = "passwordExpirationTime";
    public static final String PHONES = "phones";
    public static final String PROFILE = "profile";
    public static final String SALES_SETTINGS = "salesSettings";
    public static final String SERVICE_SETTINGS = "serviceSettings";
    public static final String SIGNATURE = "signature";
    public static final String STAFF_GROUP = "staffGroup";

    public static final Schema SCHEMA = Schema.recordOf(
      "account-record",
      Schema.Field.of(ID, Schema.nullableOf(Schema.of(Schema.Type.INT))),
      Schema.Field.of(CREATED_TIME, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(UPDATED_TIME, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(LOOKUP_NAME, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(ACCOUNT_HIERARCHY, Schema.nullableOf(LinkedObject.schema("account-hierarchy"))),
      Schema.Field.of(ATTRIBUTES, AccountAttributes.SCHEMA),
      Schema.Field.of(COUNTRY, Schema.nullableOf(LinkedObject.schema("country"))),
      Schema.Field.of(DISPLAY_NAME, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(DISPLAY_ORDER, Schema.nullableOf(Schema.of(Schema.Type.INT))),
      Schema.Field.of(EMAIL_NOTIFICATION, Schema.nullableOf(IdLookupName.schema("email-notification"))),
      // TODO emails must extend oracle object resource?
      Schema.Field.of(EMAILS, Schema.nullableOf(AccountEmails.SCHEMA)),
      Schema.Field.of(LOGIN, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(MANAGER, Schema.nullableOf(IdLookupName.schema("manager"))),
      Schema.Field.of(NAME, Schema.nullableOf(AccountName.schema("name"))),
      Schema.Field.of(NAME_FURIGANA, Schema.nullableOf(AccountName.schema("name-furigana"))),
      Schema.Field.of(NOTIFICATION_PENDING, Schema.nullableOf(Schema.of(Schema.Type.BOOLEAN))),
      Schema.Field.of(PASSWORD_EXPIRATION_TIME, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(PHONES, Schema.nullableOf(AccountPhone.SCHEMA)),
      Schema.Field.of(PROFILE, Schema.nullableOf(IdLookupName.schema("profile"))),
      Schema.Field.of(SALES_SETTINGS, Schema.nullableOf(AccountSalesSettings.SCHEMA)),
      Schema.Field.of(SERVICE_SETTINGS, Schema.nullableOf(AccountServiceSettings.SCHEMA)),
      Schema.Field.of(SIGNATURE, Schema.nullableOf(Schema.of(Schema.Type.STRING))),
      Schema.Field.of(STAFF_GROUP, Schema.nullableOf(IdLookupName.schema("staff-group")))
    );
  }
}
